apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pi-sd-frontend"
  labels:
    app: pi-sd
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: pi-sd-frontend
          image: "riko07/pi-sd-frontend:0.5.2-kubernetes"
          imagePullPolicy: IfNotPresent
