apiVersion: v1
kind: Service
metadata:
  name: "pi-sd-frontend-service"
  labels:
    app: pi-sd
spec:
  selector:
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
